export enum FileExtensions {
  PNG = "png",
  JPEG = "jpeg",
  JPG = "jpg",
  PDF = "pdf",
  DOC = 'doc',
  DOCX = 'docx',
  XLS = 'xls',
  XLSX = 'xlsx',
  PPT = 'ppt',
  PPTX = 'pptx',
  TXT = 'txt',
  CSV = 'csv',
  RTF = 'rtf',
  ODT = 'odt',
  ODS = 'ods',
  GIF = 'gif',
}
